controllers:
    resource: ../../src/Controller/
    type: annotation
    #add prefix here to add other langages
    prefix:
        fr: '/fr'
        en: '/en'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
